#!/bin/bash

echo "=========================================="
echo "🗑️  CLEAR MEMBERS (KEEP SUPER ADMINS)"
echo "=========================================="
echo ""
echo "⚠️  WARNING: This will DELETE all members except Super Admins!"
echo ""
echo "Before running this script:"
echo "1. Make sure you have backed up your database"
echo "2. Verify which users are Super Admins"
echo "3. This action CANNOT be undone"
echo ""
echo "=========================================="
echo ""
echo "📋 SQL Script Location:"
echo "   scripts/clear_members_keep_super_admin.sql"
echo ""
echo "🔗 Run this script in Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/sbknunooplaezvwtyooi/sql/new"
echo ""
echo "📝 Steps to execute:"
echo "   1. Open Supabase SQL Editor (link above)"
echo "   2. Copy the SQL from scripts/clear_members_keep_super_admin.sql"
echo "   3. Paste into SQL Editor"
echo "   4. Review the SQL carefully"
echo "   5. Click 'Run' to execute"
echo ""
echo "=========================================="
echo ""
echo "Preview of SQL script:"
echo "=========================================="
head -50 scripts/clear_members_keep_super_admin.sql
echo ""
echo "... (see full script in scripts/clear_members_keep_super_admin.sql)"
echo ""
