-- Migration: Add Meeting-based Goals Support
-- 
-- IMPORTANT: PostgreSQL requires new enum values to be committed before they can be used.
-- This migration must be run in TWO SEPARATE steps:
--
-- Step 1: Run 20251205_add_meeting_goals_step1.sql (adds enum values)
-- Step 2: Wait for commit, then run 20251205_add_meeting_goals_step2.sql (adds columns and templates)
--
-- See the step1 and step2 files in this directory.
